name: draggable_scrollbar
description: A scrollbar that can be dragged for quickly navigation through a vertical list.
             Additional option is showing label next to scrollthumb with information about current item.
version: 0.0.4
authors:
 - Flutter Community <community@flutter.zone>
 - Marina Kuznetsova <marica.tim@gmail.com>
 - Brian Egan <brian@brianegan.com>
homepage: https://github.com/fluttercommunity/flutter-draggable-scrollbar
maintainer: Marina Kuznetsova (@marica27)

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
